### ISSUE TITLE
Request to add support for .cbr files

### ISSUE THREAD

**Issue by jabrena** [remarkableno/linux#16]
The device supports .pdf/.EPUB but I was not able to upload .cbr files. Does exist any plans for it?

many thanks in advance 

Juan Antonio

**Comment by Eeems** [comment]
This is the repo for the linux kernel for the device, and not for the user interface. It is also not a support forum. You should reach out directly to their support team for this kind of question: https://support.remarkable.com

**Comment by jabrena** [comment]
Many thanks, I will use that channel.

Juan Antonio
