### ISSUE TITLE
Possible to include the tun module/driver?

### ISSUE THREAD

**Issue by ethan4** [remarkableno/linux#2]
I would like to install zerotier-one on my reMarkable so I can upload files over the network without having it know it's local IP address. 

Is it possible to include the tun module/driver going forward so I can do this?

**Comment by ddvk** [comment]
Can't you compile it and include it on your own?

**Comment by sandsmark** [comment]
More CONFIG enabled means slower startup, and more modules means more disk usage. But as ddvk said it should be fairly easy to either build the module yourself or just compile a custom kernel with it enabled.
