### ISSUE TITLE
RM2 sources

### ISSUE THREAD

**Issue by faroit** [remarkableno/linux#7]
Is there an ETA for when the RM2 kernel sources are released?

**Comment by drasch** [comment]
+1

**Comment by sandsmark** [comment]
Sorry for the (very long) delay, but both the correct uboot and linux source is pushed now, in the zero-sugar branches in both repos:
https://github.com/reMarkable/linux/tree/zero-sugar
https://github.com/reMarkable/uboot/tree/zero-sugar

There's also a proper toolchain available:
https://storage.googleapis.com/codex-public-bucket/codex-x86_64-cortexa7hf-neon-rm11x-toolchain-2.5.2.sh

We're working on fixing all the other (L)GPL packages as well (one of the issues is that we suddenly noticed that the nice automatic GPL source handling thing in Yocto has been deprecated/broken/removed), but I'm fairly certain everything (L)GPL licensed not published on github is just the unmodified version in oe-core).

**Comment by raisjn** [comment]
@sandsmark thank you! out of curiosity: does this SDK work for building rM2 apps? We built a couple QT apps from rM1 and they did not run on the rM2 with this SDK (maybe we built the apps incorrectly?)

**Comment by sandsmark** [comment]
> @sandsmark thank you! out of curiosity: does this SDK work for building rM2 apps? We built a couple QT apps from rM1 and they did not run on the rM2 with this SDK (maybe we built the apps incorrectly?)

That's probably because of the new display stuff, unfortunately, as people have discovered it's a bit more tricky now. There's still some internal discussions on what we're going to do wrt. this and the SDK.

**Comment by alistair23** [comment]
Can the OpenEmbedded recipes be released? That would really help people figure out how to get things running.

**Comment by husnoo** [comment]
> > @sandsmark thank you! out of curiosity: does this SDK work for building rM2 apps? We built a couple QT apps from rM1 and they did not run on the rM2 with this SDK (maybe we built the apps incorrectly?)
> 
> That's probably because of the new display stuff, unfortunately, as people have discovered it's a bit more tricky now. There's still some internal discussions on what we're going to do wrt. this and the SDK.

Hi, when will the SDK be released? The moment I can build an app in C to use pen->ink display, I'll buy a Remarkable 2! At the moment I'm having a go at libremarkable, but it's moved to Rust so the C code may not be as good...

**Comment by Eeems** [comment]
> Hi, when will the SDK be released? The moment I can build an app in C to use pen->ink display, I'll buy a Remarkable 2! At the moment I'm having a go at libremarkable, but it's moved to Rust so the C code may not be as good...

You can use the provided toolchain to build applications on the rM2 using https://github.com/ddvk/remarkable2-framebuffer to drive the screen. That said the toolchain has not been updated for the 2.6 version of the OS. I've had a support ticket open since March 25th asking for an updated toolchain.

**Comment by husnoo** [comment]
Thanks, will give that a try! Does this mean the toolchain won't work with 2.6 or that features will be missing?

**Comment by Eeems** [comment]
> Does this mean the toolchain won't work with 2.6 or that features will be missing?

I believe there are some issues with 2.6 if you are building Qt applications.
